title: Haveelah's Resume Webpage
author: Haveelah Mutluri
email: haveelahmutluri02@gmail.com
description: >-
 a lil abstract of what im all about hehe. maybe a chunk from my sop.
baseurl: "/haveelah" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

